# Generated by Django 2.1.4 on 2019-04-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gwave',
            fields=[
                ('role', models.TextField()),
                ('msg', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
