# Generated by Django 2.1.4 on 2019-05-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gwave',
            name='gracedb_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gwave',
            name='received_at',
            field=models.IntegerField(default=0),
        ),
    ]
