# Generated by Django 2.1.4 on 2019-05-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwaves', '0003_auto_20190503_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='gwave',
            name='alerttype',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gwave',
            name='exploded_at',
            field=models.IntegerField(default=0),
        ),
    ]
